### ISSUE TITLE
Isn't Mining

### ISSUE THREAD

**Issue by KnightxMare** [IdleCollect/Miner.Releases.Public#3]
I've installed it but it isn't minin
![Crypto Earn_Y0gIBzScr6](https://user-images.githubusercontent.com/71931995/166552287-a114bf36-7d01-4b73-a0d7-6b5249ee85c4.png)
g

**Comment by OnlyQubes** [comment]
Hi, I'll look into this, in the meantime could you answer a few questions?

How long have you been running it for? What GPU do you have?
Could you also upload the following files here:
`%appdata%\crypto.earn\Logs\miner.txt`
`%appdata%\crypto.earn\miners\comms.out`

**Comment by KnightxMare** [comment]
for about an hour but it shoes 0 H/s, Its a intel integrated GPU(bad ik)

I've tried salad.com miner but it was slow af so I'm trying this

[miner.txt](https://github.com/IdleCollect/Miner.Releases.Public/files/8614146/miner.txt)

there isn't a comms.out

**Comment by KnightxMare** [comment]
![Crypto Earn_KAyWggdBJn](https://user-images.githubusercontent.com/71931995/166562547-c28699a3-8e35-43bf-957c-83c168dc4565.png)

Showing active for sometime but isnt mining

**Comment by Xevier1** [comment]
> for about an hour but it shoes 0 H/s, Its a intel integrated GPU(bad ik)
> 
> I've tried salad.com miner but it was slow af so I'm trying this

Do note that you'll likely have the same thing here, as integrated GPU's produce next to nothing universally.
This is a valid issue by the way, we'll investigate and see if we can issue a fix soon.

**Comment by KnightxMare** [comment]
well how accurate is the 61$/month

**Comment by OnlyQubes** [comment]
Sadly 61$/month was not accurate, those were placeholder numbers until it gets enough data. Version 1.1 (soon to be released) will now lookup your GPUs name to see historical results, instead of waiting for data to be collected, so it will be more accurate now.
