### ISSUE TITLE
Not updating

### ISSUE THREAD

**Issue by Prenze1** [IdleCollect/Miner.Releases.Public#4]
Okay so ive been mining for more than 2hours (it says mining eth btw), but it hasnt updated yet or did i not earn anything yet?

**Comment by OnlyQubes** [comment]
Hi,

What is your username on the website? I can look into your account logs based on that. Could you also reply with what GPU you have?

Thanks

**Comment by Prenze1** [comment]
its "jiro4851" and its been 1d idk i still have no balance

**Comment by Prenze1** [comment]
also i have **NVIDIA GeForce 820M**

**Comment by OnlyQubes** [comment]
Hi,

Sadly this GPU is not good enough to mine crypto currency on, thus it cannot generate any balance (or could generate 0.01$ per month according to some sites).
