### ISSUE TITLE
Not mining on a powerful computer

### ISSUE THREAD

**Issue by Backup2008wastaken** [IdleCollect/Miner.Releases.Public#5]
my pc specs are 32gb ram 2666mhz, an i5 9600k, and a 6600xt. I have a sneaking suspicion that this program is just bullshit and steals your information because I have 61$ monthly projected income, and someone with a much weaker system on the issues forum has the same projected income.

My issue is the same as his, [https://github.com/IdleCollect/Miner.Releases.Public/issues/3](url), and when it's "mining" it doesn't use any system resources, which is very odd.

**Comment by OnlyQubes** [comment]
Hi,

The 61$ projection is based on a default value that will update when it starts mining and then that value will be re-calculated. The prediction system will be re-worked in the near future, so it should be a lot clearer then.

For the non-mining issue could you provide these files:
`%appdata%\crypto.earn\Logs\miner.txt`
`%appdata%\crypto.earn\miners\comms.out`

Additionally your username or email on idlecollect.com would be also extremely helpful, so we could look into the logs on our system as well.

**Comment by OnlyQubes** [comment]
If you wouldn't like to share this information publicly you can either send this data to OnlyQubes@Sadonis.org as well and I can look into it through that as well, we can also setup communications through discord if you'd like that.

**Comment by Xevier1** [comment]
Do keep in mind that while the data **is** incorrect for reasons that OnlyQubes has told you, your system specs are also not amazing in terms of mining performance. Really the only thing that is used is the GPU, and according to NiceHash it's estimated that your GPU (AMD RX 6600 XT 8GB i assume) only mines around $1/day or so. 

As for your sneaking suspicion, you can put that to rest. The code is publicly viewable, we are not able to steal your information. https://github.com/IdleCollect/Miner.Source.App
